### POST product
POST localhost:8080/api/product
Content-Type: application/json

{
  "name": "Cucurella",
  "description": "Hahahah",
  "skuCode": "cucu",
  "price": 1200
}

### GET products
GET localhost:8080/api/product